[project]
name = "blu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.50",
    "docling>=2.73.1",
    "pymongo>=4.16.0",
    "sentence-transformers>=5.2.2",
]
